swagger: "2.0"

info:
  title: "Exchange App (sf-academy)"
  description: "This is the server for Exchange App"
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
  contact:
    name: "Exchange App Support"
    email: "support@sf-academy-exchange.io"
  license:
    name: "Apache 2.0"
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"

basePath: "/v1"

tags:
  - name: "exchange"
    description: "Everything about exchange currency"
  - name: "user"
    description: "Everything about user"

paths: {}

definitions:
  Error:
    properties:
      message:
        type: "string"

securityDefinitions:
  apiKey:
    type: apiKey
    in: header
    name: token
