swagger: "2.0"

info:
  title: "Exchange App (sf-academy)"
  description: "This is the server for Exchange App"
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
  contact:
    name: "Exchange App Support"
    email: "support@sf-academy-exchange.io"
  license:
    name: "Apache 2.0"
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"

basePath: "/v1"

tags:
  - name: "exchange"
    description: "Everithing about exchange currency"

paths:
  /rates:
    get:
      tags:
        - "exchange"
      description: "Get current currency rates"
      summary: "Get current currency rates"
      operationId: "getExchangeRates"
      produces:
        - "application/json"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "object"
            additionalProperties:
              type: "number"
              format: "float"
        default:
          description: "Fail operation"
          schema:
            $ref: "#/definitions/Error"

definitions:
  Error:
    properties:
      message:
        type: "string"
